services:     
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"    
    volumes:
      - './app:/code/app'
    depends_on:
      - teamC_mysql
    env_file: 
      - .env
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}

  teamC_mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      Lang: C.UTF-8
    ports:
      - "3307:3306"  
    volumes:
      - ./db_data:/var/lib/mysql

  teamC_redis:
    image: redis:latest
    ports: 
      - "6380:6379"
    volumes: 
      - /var/lib/docker/volumes/redis/_data
      - /app/redis.conf
    command: redis-server /app/redis.conf