version: '3'

services:     
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"    
    volumes:
      - './app:/code/app'
    depends_on:
      - teamC_mysql
    env_file: 
      - .env
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}

  teamC_mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      Lang: C.UTF-8
    ports:
      - "3307:3306"  
    volumes:
      - ./db_data:/var/lib/mysql

  teamC_redis:
    image: redis:latest
    ports: 
      - "6380:6379"
    volumes: 
      - /var/lib/docker/volumes/redis/_data
      - /app/redis.conf
    command: redis-server /app/redis.conf

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    ports:
      - "8080:8080" 
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      
  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:9.5.20
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning 
      - ./grafana/data:/var/lib/grafana 
    ports:
      - "3000:3000" 
  
networks:
  app-network:
    driver: bridge
